import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import Image from "next/image";
import PostsList from "./posts";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Social Media App </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col items-center justify-center gap-4">
          <p className="text-center text-2xl text-white">
            {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
          </p>
          {sessionData && (
            <Image
              className="rounded-full"
              width={40}
              height={40}
              src={sessionData.user?.image ?? "/default-image.jpg"}
              alt="user image"
            />
          )}
          <button
            className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
            onClick={
              sessionData ? () => void signOut() : () => void signIn("google")
            }
          >
            {sessionData ? "Sign out" : "Sign in"}
          </button>
        </div>
        <PostsList />
      </main>
    </>
  );
};

export default Home;
