import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";
import { api } from "y/utils/api";

const UserProfile: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  const name = Array.isArray(id) ? id[0] : id;
  const { data: userProfile } = api.users.getUserByName.useQuery({
    name: name || "",
  });
  return (
    <>
      <Head>
        <title>{userProfile?.name} Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {userProfile?.name}
        <Image
          src={userProfile?.image || ""}
          alt="author image"
          width={50}
          height={50}
        />
      </div>
      <div>
        {userProfile?.posts?.map((post) => {
          return <div key={post.id}>{post.content}</div>;
        })}
      </div>
    </>
  );
};

export default UserProfile;
